Repository google/or-tools, pull requests merged in 2018-04, with the labels that each got.

#661 Fix wrong marshall copy size for CppProtoType in C# wrapper
  ortools/util/csharp/proto.i
Labels: .NET, Bug

#638 Add parameter passing to the CBC interface
  ortools/linear_solver/cbc_interface.cc
Labels: C++, Feature Request

#664 Update model_exporter.cc
  ortools/linear_solver/model_exporter.cc
Labels: C++, Feature Request

#670 Update LICENSE with copyright date and owner
  LICENSE-2.0.txt
Labels: Bug
